name: ci

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set VERSION variable
      run: echo "VERSION=1.0.0" >> $GITHUB_ENV

    - name: Build
      run: dotnet build --configuration Release /p:Version=${{ env.VERSION }}

    - name: Test
      run: dotnet test --configuration Release /p:Version=${{ env.VERSION }} --no-build

    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${{ env.VERSION }} --no-build --output .

    - name: Push
      run: dotnet nuget push *.${{ env.VERSION }}.nupkg --source https://nuget.pkg.github.com/IT247PRO/index.json --api-key ${{ secrets.CI_ACTION_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.CI_ACTION_TOKEN }}
